name       : capnproto
version    : 1.0.1
release    : 5
source     :
    - https://github.com/capnproto/capnproto/archive/refs/tags/v1.0.1.tar.gz : 5bdb16f6b389a9e29b04214b9bae1759e8b7fe2b45049d7e3f1f286ba050a200
homepage   : https://capnproto.org/
license    : MIT
component  : programming
summary    : Cap’n Proto is an insanely fast data interchange format and capability-based RPC system
description: |
    Cap’n Proto is an insanely fast data interchange format and capability-based RPC system. Think JSON, except binary. Or think Protocol Buffers, except faster. In fact, in benchmarks, Cap’n Proto is INFINITY TIMES faster than Protocol Buffers.
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
