name       : capnproto
version    : 0.8.0
release    : 1
source     :
    - https://capnproto.org/capnproto-c++-0.8.0.tar.gz : d1f40e47574c65700f0ec98bf66729378efabe3c72bc0cda795037498541c10d
license    : MIT
component  : programming
summary    : Cap’n Proto is an insanely fast data interchange format and capability-based RPC system
description: |
    Cap’n Proto is an insanely fast data interchange format and capability-based RPC system
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
