name       : capnproto
version    : 0.9.0
release    : 3
source     :
    - https://capnproto.org/capnproto-c++-0.9.0.tar.gz : b28054a7a2bfea42bfc392c8d009630d94d72e8ce86a23ad6f18b5e72574064f
license    : MIT
component  : programming
summary    : Cap’n Proto is an insanely fast data interchange format and capability-based RPC system
description: |
    Cap’n Proto is an insanely fast data interchange format and capability-based RPC system
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
